AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: An example RESTful service
Resources:
  DatasetCRUD:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: ./bin/datasets/main.zip
      Runtime: go1.x
      Timeout: 60
      Environment:
        Variables:
          TABLE_NAME: "datasets"
          IS_DEV: true
      Events:
        DatasetCL:
          Type: Api
          Properties:
            Path: /dataset
            Method: ANY
        DatasetRUD:
          Type: Api
          Properties:
            Path: /dataset/{id+}
            Method: ANY

  NotificationCRUD:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: ./bin/notifications/main.zip
      Runtime: go1.x
      Timeout: 60
      Environment:
        Variables:
          TABLE_NAME: "notification"
          IS_DEV: true
      Events:
        NotificationCL:
          Type: Api
          Properties:
            Path: /notification
            Method: ANY
        NotificationRUD:
          Type: Api
          Properties:
            Path: /notification/{id+}
            Method: ANY

  CampaingCRUD:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: ./bin/campaings/main.zip
      Runtime: go1.x
      Timeout: 60
      Environment:
        Variables:
          TABLE_NAME: "campaing"
          IS_DEV: true
      Events:
        CampaingCL:
          Type: Api
          Properties:
            Path: /campaing
            Method: ANY
        CampaingRUD:
          Type: Api
          Properties:
            Path: /campaing/{id+}
            Method: ANY
